/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BetterMermaidPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  language: "en",
  customCss: "",
  enableClickToZoom: true,
  modalWidthPercent: 80,
  modalHeightPercent: 80
};
var STRINGS = {
  en: {
    settingsTitle: "Better Mermaid Settings",
    languageLabel: "Language",
    languageDesc: "Display language for plugin UI",
    enableClickToZoom: "Enable click to zoom",
    enableClickToZoomDesc: "Click on a Mermaid diagram in reading mode to view it enlarged",
    modalWidth: "Modal width",
    modalWidthDesc: "Width of the zoom modal (percentage of viewport)",
    modalHeight: "Modal height",
    modalHeightDesc: "Height of the zoom modal (percentage of viewport)",
    customCss: "Custom CSS",
    customCssDesc: "CSS to inject into Obsidian (applies immediately)",
    customCssPlaceholder: "/* Enter your custom CSS here */",
    reset: "Reset to default",
    downloadPng: "Download PNG",
    zoom: "Zoom",
    converting: "Converting..."
  },
  zh: {
    settingsTitle: "Better Mermaid \u8BBE\u7F6E",
    languageLabel: "\u8BED\u8A00",
    languageDesc: "\u63D2\u4EF6\u754C\u9762\u7684\u663E\u793A\u8BED\u8A00",
    enableClickToZoom: "\u542F\u7528\u5355\u51FB\u653E\u5927",
    enableClickToZoomDesc: "\u5728\u9605\u8BFB\u6A21\u5F0F\u4E0B\u5355\u51FB Mermaid \u56FE\u8868\u4EE5\u653E\u5927\u67E5\u770B",
    modalWidth: "\u5F39\u7A97\u5BBD\u5EA6",
    modalWidthDesc: "\u5F39\u7A97\u5BBD\u5EA6\uFF08\u89C6\u53E3\u767E\u5206\u6BD4\uFF09",
    modalHeight: "\u5F39\u7A97\u9AD8\u5EA6",
    modalHeightDesc: "\u5F39\u7A97\u9AD8\u5EA6\uFF08\u89C6\u53E3\u767E\u5206\u6BD4\uFF09",
    customCss: "\u81EA\u5B9A\u4E49 CSS",
    customCssDesc: "\u6CE8\u5165\u5230 Obsidian \u7684 CSS\uFF08\u5373\u65F6\u751F\u6548\uFF09",
    customCssPlaceholder: "/* \u5728\u8FD9\u91CC\u8F93\u5165\u81EA\u5B9A\u4E49 CSS */",
    reset: "\u91CD\u7F6E\u4E3A\u9ED8\u8BA4\u503C",
    downloadPng: "\u4E0B\u8F7D PNG",
    zoom: "\u7F29\u653E",
    converting: "\u8F6C\u6362\u4E2D..."
  }
};
function i18n(lang, key) {
  var _a, _b;
  const dict = (_a = STRINGS[lang]) != null ? _a : STRINGS["en"];
  return (_b = dict[key]) != null ? _b : key;
}
var BetterMermaidSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  t(key) {
    return i18n(this.plugin.settings.language, key);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const s = this.plugin.settings;
    new import_obsidian.Setting(containerEl).setName(this.t("settingsTitle")).setHeading();
    new import_obsidian.Setting(containerEl).setName(this.t("languageLabel")).setDesc(this.t("languageDesc")).addDropdown(
      (dropdown) => dropdown.addOption("en", "English").addOption("zh", "\u4E2D\u6587").setValue(s.language).onChange(async (value) => {
        s.language = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName(this.t("enableClickToZoom")).setDesc(this.t("enableClickToZoomDesc")).addToggle(
      (toggle) => toggle.setValue(s.enableClickToZoom).onChange(async (value) => {
        s.enableClickToZoom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(this.t("modalWidth")).setDesc(this.t("modalWidthDesc")).addSlider(
      (slider) => slider.setLimits(30, 100, 5).setValue(s.modalWidthPercent).onChange(async (value) => {
        s.modalWidthPercent = value;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText(this.t("reset")).onClick(async () => {
        s.modalWidthPercent = DEFAULT_SETTINGS.modalWidthPercent;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName(this.t("modalHeight")).setDesc(this.t("modalHeightDesc")).addSlider(
      (slider) => slider.setLimits(30, 100, 5).setValue(s.modalHeightPercent).onChange(async (value) => {
        s.modalHeightPercent = value;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText(this.t("reset")).onClick(async () => {
        s.modalHeightPercent = DEFAULT_SETTINGS.modalHeightPercent;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName(this.t("customCss")).setDesc(this.t("customCssDesc")).addTextArea(
      (textarea) => textarea.setPlaceholder(this.t("customCssPlaceholder")).setValue(s.customCss).onChange(async (value) => {
        s.customCss = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/modal.ts
var import_obsidian2 = require("obsidian");
var ZOOM_OPTIONS = [
  { label: "20%", value: 0.2 },
  { label: "50%", value: 0.5 },
  { label: "75%", value: 0.75 },
  { label: "100%", value: 1 }
];
var MermaidImageModal = class extends import_obsidian2.Modal {
  constructor(app, svg, settings) {
    super(app);
    this.scale = 1;
    this.panX = 0;
    this.panY = 0;
    this.isDragging = false;
    this.dragStartX = 0;
    this.dragStartY = 0;
    this.panStartX = 0;
    this.panStartY = 0;
    this.onWheel = (e) => {
      e.preventDefault();
      if (e.ctrlKey) {
        const rect = this.viewport.getBoundingClientRect();
        const mx = e.clientX - rect.left;
        const my = e.clientY - rect.top;
        const factor = 1 - e.deltaY * 5e-3;
        const newScale = Math.max(0.1, Math.min(10, this.scale * factor));
        this.panX = mx - (mx - this.panX) * (newScale / this.scale);
        this.panY = my - (my - this.panY) * (newScale / this.scale);
        this.scale = newScale;
        this.syncZoomDisplay(newScale);
      } else if (e.shiftKey) {
        this.panX -= e.deltaY;
      } else {
        this.panY -= e.deltaY;
      }
      this.applyTransform();
    };
    this.onMouseDown = (e) => {
      if (e.button !== 0)
        return;
      const target = e.target;
      if (target.closest(".better-mermaid-controls"))
        return;
      this.isDragging = true;
      this.dragStartX = e.clientX;
      this.dragStartY = e.clientY;
      this.panStartX = this.panX;
      this.panStartY = this.panY;
      this.viewport.addClass("better-mermaid-grabbing");
    };
    this.onMouseMove = (e) => {
      if (!this.isDragging)
        return;
      this.panX = this.panStartX + (e.clientX - this.dragStartX);
      this.panY = this.panStartY + (e.clientY - this.dragStartY);
      this.applyTransform();
    };
    this.onMouseUp = () => {
      if (!this.isDragging)
        return;
      this.isDragging = false;
      this.viewport.removeClass("better-mermaid-grabbing");
    };
    this.svg = svg;
    this.settings = settings;
    this.modalEl.addClass("better-mermaid-modal-size");
  }
  t(key) {
    return i18n(this.settings.language, key);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("better-mermaid-modal");
    this.svgEl = this.svg.cloneNode(true);
    this.svgEl.removeAttribute("width");
    this.svgEl.removeAttribute("height");
    this.svgEl.addClass("better-mermaid-svg");
    this.viewport = contentEl.createDiv({ cls: "better-mermaid-viewport" });
    this.viewport.appendChild(this.svgEl);
    const controls = this.viewport.createDiv({ cls: "better-mermaid-controls" });
    controls.createEl("label", { text: this.t("zoom") });
    this.zoomSelect = controls.createEl("select");
    ZOOM_OPTIONS.forEach((opt) => {
      const option = this.zoomSelect.createEl("option");
      option.value = String(opt.value);
      option.text = opt.label;
    });
    this.zoomSelect.value = "1";
    this.zoomSelect.addEventListener("change", () => {
      const gen = this.zoomSelect.querySelector("[data-generated]");
      if (gen)
        gen.remove();
      this.setZoom(parseFloat(this.zoomSelect.value));
    });
    const btn = controls.createEl("button", { text: this.t("downloadPng") });
    btn.addEventListener("click", () => {
      void this.handleDownload(btn);
    });
    const doc = this.viewport.ownerDocument;
    this.viewport.addEventListener("wheel", this.onWheel, { passive: false });
    this.viewport.addEventListener("mousedown", this.onMouseDown);
    doc.addEventListener("mousemove", this.onMouseMove);
    doc.addEventListener("mouseup", this.onMouseUp);
  }
  onClose() {
    const doc = this.viewport.ownerDocument;
    doc.removeEventListener("mousemove", this.onMouseMove);
    doc.removeEventListener("mouseup", this.onMouseUp);
    this.contentEl.empty();
    this.scale = 1;
    this.panX = 0;
    this.panY = 0;
    this.isDragging = false;
  }
  setZoom(scale) {
    const rect = this.viewport.getBoundingClientRect();
    const cx = rect.width / 2;
    const cy = rect.height / 2;
    this.panX = cx - (cx - this.panX) * (scale / this.scale);
    this.panY = cy - (cy - this.panY) * (scale / this.scale);
    this.scale = scale;
    this.applyTransform();
    this.syncZoomDisplay(scale);
  }
  syncZoomDisplay(scale) {
    const gen = this.zoomSelect.querySelector("[data-generated]");
    if (gen)
      gen.remove();
    const exact = ZOOM_OPTIONS.find((o) => Math.abs(o.value - scale) < 5e-3);
    if (exact) {
      this.zoomSelect.value = String(exact.value);
      return;
    }
    const doc = this.contentEl.ownerDocument;
    const opt = doc.createElement("option");
    opt.setAttribute("data-generated", "true");
    opt.value = String(scale);
    opt.text = `${Math.round(scale * 100)}%`;
    this.zoomSelect.appendChild(opt);
    this.zoomSelect.value = String(scale);
  }
  applyTransform() {
    this.svgEl.style.transform = `translate(${this.panX}px, ${this.panY}px) scale(${this.scale})`;
  }
  async handleDownload(btn) {
    btn.setText(this.t("converting"));
    btn.disabled = true;
    try {
      const pngDataUrl = await this.svgToPng();
      const doc = this.contentEl.ownerDocument;
      const link = doc.createElement("a");
      link.download = "mermaid-diagram.png";
      link.href = pngDataUrl;
      link.click();
    } catch (e) {
      console.error("Failed to convert SVG to PNG:", e);
    }
    btn.setText(this.t("downloadPng"));
    btn.disabled = false;
  }
  svgToPng() {
    const cloned = this.svg.cloneNode(true);
    const viewBox = cloned.getAttribute("viewBox");
    if (viewBox) {
      const parts = viewBox.split(/\s+/).map(Number);
      if (parts.length === 4) {
        cloned.setAttribute("width", String(parts[2]));
        cloned.setAttribute("height", String(parts[3]));
      }
    }
    const serializer = new XMLSerializer();
    const svgString = serializer.serializeToString(cloned);
    const dataUrl = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svgString);
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => {
        const doc = this.contentEl.ownerDocument;
        const canvas = doc.createElement("canvas");
        const pxRatio = 2;
        canvas.width = img.width * pxRatio;
        canvas.height = img.height * pxRatio;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          reject(new Error("Failed to get canvas context"));
          return;
        }
        ctx.scale(pxRatio, pxRatio);
        ctx.fillStyle = "#ffffff";
        ctx.fillRect(0, 0, img.width, img.height);
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      };
      img.onerror = () => {
        reject(new Error("Failed to load SVG image"));
      };
      img.src = dataUrl;
    });
  }
};

// src/main.ts
var BetterMermaidPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.cssSheet = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BetterMermaidSettingTab(this.app, this));
    this.injectCSS();
    this.registerDomEvent(
      this.app.workspace.containerEl,
      "click",
      (evt) => {
        if (!this.settings.enableClickToZoom)
          return;
        const target = evt.target;
        const mermaidContainer = target.closest("div.mermaid");
        if (!mermaidContainer)
          return;
        const mermaidSvg = mermaidContainer.querySelector("svg");
        if (!mermaidSvg)
          return;
        new MermaidImageModal(
          this.app,
          mermaidSvg,
          this.settings
        ).open();
      },
      true
    );
  }
  onunload() {
    this.removeCSS();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.injectCSS();
  }
  injectCSS() {
    this.removeCSS();
    const sizing = `
.better-mermaid-modal-size {
  width: ${this.settings.modalWidthPercent}vw;
  max-width: ${this.settings.modalWidthPercent}vw;
  max-height: ${this.settings.modalHeightPercent}vh;
}`;
    const allCss = sizing + "\n" + (this.settings.customCss || "");
    if (!allCss.trim())
      return;
    try {
      this.cssSheet = new CSSStyleSheet();
      this.cssSheet.replaceSync(allCss);
      const doc = this.app.workspace.containerEl.ownerDocument;
      doc.adoptedStyleSheets = [
        ...doc.adoptedStyleSheets,
        this.cssSheet
      ];
    } catch (e) {
    }
  }
  removeCSS() {
    if (this.cssSheet) {
      const doc = this.app.workspace.containerEl.ownerDocument;
      doc.adoptedStyleSheets = Array.from(
        doc.adoptedStyleSheets
      ).filter((s) => s !== this.cssSheet);
      this.cssSheet = null;
    }
  }
};

/* nosourcemap */