/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MermaidZoomPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MermaidZoomPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.zoomStates = /* @__PURE__ */ new Map();
    this.defaultMinScale = 0.1;
    this.defaultMaxScale = 5;
    this.defaultScale = 1;
    this.processedElements = /* @__PURE__ */ new WeakSet();
  }
  onload() {
    console.debug("Loading Mermaid Zoom plugin");
    this.setupMutationObserver();
    this.setupResizeObserver();
    this.app.workspace.onLayoutReady(() => {
      this.processAllMermaidDiagrams();
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.processAllMermaidDiagrams();
    }));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
      this.processAllMermaidDiagrams();
    }));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      setTimeout(() => this.processAllMermaidDiagrams(), 200);
    }));
  }
  setupResizeObserver() {
    this.resizeObserver = new ResizeObserver((entries) => {
      var _a;
      for (const entry of entries) {
        const container = entry.target;
        if (!document.contains(container)) {
          (_a = this.resizeObserver) == null ? void 0 : _a.unobserve(container);
          const contentWrapper2 = container.querySelector(".mermaid-zoom-content");
          if (contentWrapper2) {
            this.zoomStates.delete(contentWrapper2);
          }
          continue;
        }
        const contentWrapper = container.querySelector(".mermaid-zoom-content");
        if (!contentWrapper)
          continue;
        const state = this.zoomStates.get(contentWrapper);
        if (state) {
          this.fitToContainer(container, contentWrapper, state.svg, state);
        }
      }
    });
  }
  setupMutationObserver() {
    this.mutationObserver = new MutationObserver((mutations) => {
      for (const mutation of Array.from(mutations)) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLElement || node instanceof SVGElement) {
            this.processPotentialMermaidElement(node);
          }
        }
      }
    });
    this.mutationObserver.observe(document.body, {
      childList: true,
      subtree: true
    });
  }
  processPotentialMermaidElement(element) {
    const mermaidSvgs = [];
    if (element instanceof HTMLElement) {
      const svgs = Array.from(element.querySelectorAll('.mermaid svg, svg[id^="mermaid-"]'));
      mermaidSvgs.push(...svgs);
      if (element.classList.contains("mermaid")) {
        const svg = element.querySelector("svg");
        if (svg)
          mermaidSvgs.push(svg);
      }
    }
    for (const svg of mermaidSvgs) {
      if (!this.processedElements.has(svg) && !this.hasZoomContainer(svg)) {
        this.wrapMermaidWithZoom(svg);
        this.processedElements.add(svg);
      }
    }
  }
  hasZoomContainer(svg) {
    var _a;
    const mermaidContainer = svg.closest(".mermaid");
    const parent = (mermaidContainer == null ? void 0 : mermaidContainer.parentElement) || svg.parentElement;
    return (_a = parent == null ? void 0 : parent.hasClass("mermaid-zoom-content")) != null ? _a : false;
  }
  processAllMermaidDiagrams() {
    const mermaidSvgs = document.querySelectorAll('.mermaid svg, svg[id^="mermaid-"]');
    for (const mermaidSvg of Array.from(mermaidSvgs)) {
      if (!this.processedElements.has(mermaidSvg) && !this.hasZoomContainer(mermaidSvg)) {
        this.wrapMermaidWithZoom(mermaidSvg);
        this.processedElements.add(mermaidSvg);
      }
    }
  }
  wrapMermaidWithZoom(svg) {
    var _a;
    if (!svg.parentElement)
      return;
    const mermaidContainer = svg.closest(".mermaid");
    const targetParent = (mermaidContainer == null ? void 0 : mermaidContainer.parentElement) || svg.parentElement;
    const targetElement = mermaidContainer || svg;
    if (!targetParent)
      return;
    const initialSvgRect = svg.getBoundingClientRect();
    const initialSvgHeight = initialSvgRect.height || 200;
    const parentWidth = targetParent.clientWidth || 600;
    const containerHeight = Math.min(initialSvgHeight + 60, parentWidth);
    const container = createDiv("mermaid-zoom-container");
    container.style.cssText = `
			position: relative;
			overflow: hidden;
			width: 100%;
			height: ${containerHeight}px;
			min-width: 150px;
			min-height: 100px;
			background: var(--background-secondary);
			border-radius: 8px;
			border: 1px solid var(--background-modifier-border);
			margin: 1em 0;
			padding: 1em;
			padding-bottom: 2.5em;
			box-sizing: border-box;
		`;
    const contentWrapper = container.createDiv("mermaid-zoom-content");
    contentWrapper.style.cssText = `
			transform-origin: 0 0;
			transition: transform 0.1s ease-out;
			width: fit-content;
		`;
    targetParent.insertBefore(container, targetElement);
    contentWrapper.appendChild(targetElement);
    const svgRect = svg.getBoundingClientRect();
    const svgOriginalWidth = svgRect.width || svg.clientWidth || 300;
    const svgOriginalHeight = svgRect.height || svg.clientHeight || 200;
    const state = {
      scale: this.defaultScale,
      minScale: this.defaultMinScale,
      maxScale: this.defaultMaxScale,
      isDragging: false,
      startX: 0,
      startY: 0,
      translateX: 0,
      translateY: 0,
      svg,
      container,
      svgOriginalWidth,
      svgOriginalHeight
    };
    this.zoomStates.set(contentWrapper, state);
    this.register(this.createControls(container, contentWrapper, state));
    this.register(this.addWheelZoom(container, contentWrapper, state));
    this.register(this.addDragPan(container, contentWrapper, state));
    this.register(this.addTouchGestures(container, contentWrapper, state));
    this.fitToContainer(container, contentWrapper, svg, state);
    (_a = this.resizeObserver) == null ? void 0 : _a.observe(container);
  }
  fitToContainer(container, contentWrapper, svg, state) {
    if (container.clientWidth <= 0 || container.clientHeight <= 0)
      return;
    if (state.svgOriginalWidth <= 0 || state.svgOriginalHeight <= 0)
      return;
    const computedStyle = getComputedStyle(container);
    const paddingLeft = parseFloat(computedStyle.paddingLeft) || 0;
    const paddingRight = parseFloat(computedStyle.paddingRight) || 0;
    const paddingTop = parseFloat(computedStyle.paddingTop) || 0;
    const paddingBottom = parseFloat(computedStyle.paddingBottom) || 0;
    const availableWidth = container.clientWidth - paddingLeft - paddingRight;
    const availableHeight = container.clientHeight - paddingTop - paddingBottom;
    const svgWidth = state.svgOriginalWidth;
    const svgHeight = state.svgOriginalHeight;
    const scaleX = availableWidth / svgWidth;
    const scaleY = availableHeight / svgHeight;
    const fitScale = Math.min(scaleX, scaleY, 1);
    const scaledWidth = svgWidth * fitScale;
    const scaledHeight = svgHeight * fitScale;
    const centerX = (container.clientWidth - scaledWidth) / 2 - paddingLeft;
    const centerY = (container.clientHeight - scaledHeight) / 2 - paddingTop;
    state.scale = fitScale;
    state.translateX = centerX;
    state.translateY = Math.max(0, centerY);
    this.updateTransform(contentWrapper, state);
  }
  openFullscreenModal(state) {
    const modal = document.createElement("div");
    modal.className = "mermaid-zoom-modal";
    modal.style.cssText = `
			position: fixed;
			top: 0;
			left: 0;
			width: 100vw;
			height: 100vh;
			background: var(--background-primary);
			z-index: 9999;
			display: flex;
			flex-direction: column;
		`;
    const header = document.createElement("div");
    header.className = "mermaid-zoom-modal-header";
    header.style.cssText = `
			display: flex;
			justify-content: flex-end;
			padding: 10px 15px;
			background: var(--background-secondary);
			border-bottom: 1px solid var(--background-modifier-border);
		`;
    const closeBtn = document.createElement("button");
    closeBtn.className = "mermaid-zoom-modal-close";
    closeBtn.textContent = "\u2715";
    closeBtn.style.cssText = `
			width: 32px;
			height: 32px;
			border: none;
			background: var(--interactive-normal);
			color: var(--text-normal);
			border-radius: 4px;
			cursor: pointer;
			font-size: 18px;
			display: flex;
			align-items: center;
			justify-content: center;
			transition: background 0.2s;
		`;
    header.appendChild(closeBtn);
    const content = document.createElement("div");
    content.className = "mermaid-zoom-modal-content";
    content.style.cssText = `
			flex: 1;
			overflow: hidden;
			position: relative;
			display: flex;
			align-items: center;
			justify-content: center;
		`;
    const modalZoomContainer = document.createElement("div");
    modalZoomContainer.className = "mermaid-zoom-modal-zoom-container";
    modalZoomContainer.style.cssText = `
			width: 100%;
			height: 100%;
			overflow: hidden;
			position: relative;
		`;
    const modalContentWrapper = document.createElement("div");
    modalContentWrapper.className = "mermaid-zoom-modal-wrapper";
    modalContentWrapper.style.cssText = `
			transform-origin: 0 0;
			transition: transform 0.1s ease-out;
			width: fit-content;
			position: absolute;
		`;
    const svgClone = state.svg.cloneNode(true);
    modalContentWrapper.appendChild(svgClone);
    modalZoomContainer.appendChild(modalContentWrapper);
    content.appendChild(modalZoomContainer);
    const controls = document.createElement("div");
    controls.className = "mermaid-zoom-modal-controls";
    controls.style.cssText = `
			position: absolute;
			bottom: 20px;
			right: 20px;
			display: flex;
			gap: 5px;
			background: var(--background-secondary);
			padding: 8px;
			border-radius: 8px;
			box-shadow: 0 4px 12px rgba(0,0,0,0.2);
		`;
    const modalState = {
      scale: 1,
      minScale: this.defaultMinScale,
      maxScale: this.defaultMaxScale,
      isDragging: false,
      startX: 0,
      startY: 0,
      translateX: 0,
      translateY: 0,
      svg: svgClone,
      container: modalZoomContainer,
      svgOriginalWidth: state.svgOriginalWidth,
      svgOriginalHeight: state.svgOriginalHeight
    };
    const zoomInBtn = document.createElement("button");
    zoomInBtn.textContent = "+";
    this.styleButton(zoomInBtn);
    zoomInBtn.addEventListener("click", () => this.zoom(modalContentWrapper, modalState, 1.2));
    const zoomOutBtn = document.createElement("button");
    zoomOutBtn.textContent = "-";
    this.styleButton(zoomOutBtn);
    zoomOutBtn.addEventListener("click", () => this.zoom(modalContentWrapper, modalState, 0.8));
    const resetBtn = document.createElement("button");
    resetBtn.textContent = "\u27F2";
    this.styleButton(resetBtn);
    resetBtn.addEventListener("click", () => {
      this.fitToContainerModal(modalZoomContainer, modalContentWrapper, modalState);
    });
    const scaleIndicator = document.createElement("span");
    scaleIndicator.style.cssText = `
			padding: 4px 8px;
			font-size: 12px;
			font-family: var(--font-ui-medium);
			color: var(--text-muted);
			min-width: 45px;
			text-align: center;
		`;
    modalState.scaleIndicator = scaleIndicator;
    controls.appendChild(zoomInBtn);
    controls.appendChild(zoomOutBtn);
    controls.appendChild(resetBtn);
    controls.appendChild(scaleIndicator);
    content.appendChild(controls);
    modal.appendChild(header);
    modal.appendChild(content);
    const modalCleanupFns = [];
    modalCleanupFns.push(this.addWheelZoom(modalZoomContainer, modalContentWrapper, modalState));
    modalCleanupFns.push(this.addDragPan(modalZoomContainer, modalContentWrapper, modalState));
    modalCleanupFns.push(this.addTouchGestures(modalZoomContainer, modalContentWrapper, modalState));
    const closeModal = () => {
      for (const cleanup of modalCleanupFns) {
        cleanup();
      }
      modal.remove();
      document.removeEventListener("keydown", handleKeydown);
    };
    const handleKeydown = (e) => {
      if (e.key === "Escape") {
        closeModal();
      }
    };
    document.addEventListener("keydown", handleKeydown);
    closeBtn.addEventListener("click", closeModal);
    document.body.appendChild(modal);
    requestAnimationFrame(() => {
      this.fitToContainerModal(modalZoomContainer, modalContentWrapper, modalState);
    });
  }
  fitToContainerModal(container, contentWrapper, state) {
    if (container.clientWidth <= 0 || container.clientHeight <= 0)
      return;
    if (state.svgOriginalWidth <= 0 || state.svgOriginalHeight <= 0)
      return;
    const padding = 40;
    const availableWidth = container.clientWidth - padding * 2;
    const availableHeight = container.clientHeight - padding * 2;
    const svgWidth = state.svgOriginalWidth;
    const svgHeight = state.svgOriginalHeight;
    const scaleX = availableWidth / svgWidth;
    const scaleY = availableHeight / svgHeight;
    const fitScale = Math.min(scaleX, scaleY, 2);
    const scaledWidth = svgWidth * fitScale;
    const scaledHeight = svgHeight * fitScale;
    const centerX = (container.clientWidth - scaledWidth) / 2;
    const centerY = (container.clientHeight - scaledHeight) / 2;
    state.scale = fitScale;
    state.translateX = centerX;
    state.translateY = centerY;
    this.updateTransform(contentWrapper, state);
  }
  createControls(container, contentWrapper, state) {
    const controls = container.createDiv("mermaid-zoom-controls");
    controls.style.cssText = `
			position: absolute;
			bottom: 10px;
			right: 10px;
			display: flex;
			gap: 5px;
			z-index: 100;
			background: var(--background-secondary);
			padding: 5px;
			border-radius: 5px;
			box-shadow: 0 2px 8px rgba(0,0,0,0.15);
		`;
    const zoomInBtn = controls.createEl("button", {
      text: "+",
      cls: "mermaid-zoom-btn"
    });
    this.styleButton(zoomInBtn);
    zoomInBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.zoom(contentWrapper, state, 1.2);
    });
    const zoomOutBtn = controls.createEl("button", {
      text: "-",
      cls: "mermaid-zoom-btn"
    });
    this.styleButton(zoomOutBtn);
    zoomOutBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.zoom(contentWrapper, state, 0.8);
    });
    const resetBtn = controls.createEl("button", {
      text: "\u27F2",
      cls: "mermaid-zoom-btn"
    });
    this.styleButton(resetBtn);
    resetBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.resetZoom(contentWrapper, state);
    });
    const scaleIndicator = controls.createEl("span", {
      cls: "mermaid-zoom-scale"
    });
    scaleIndicator.style.cssText = `
			padding: 4px 8px;
			font-size: 12px;
			font-family: var(--font-ui-medium);
			color: var(--text-muted);
			min-width: 45px;
			text-align: center;
		`;
    state.scaleIndicator = scaleIndicator;
    this.updateTransform(contentWrapper, state);
    const fullscreenBtn = controls.createEl("button", {
      cls: "mermaid-zoom-btn mermaid-fullscreen-btn"
    });
    const svgNS = "http://www.w3.org/2000/svg";
    const svg = document.createElementNS(svgNS, "svg");
    svg.setAttribute("width", "24");
    svg.setAttribute("height", "24");
    svg.setAttribute("viewBox", "0 0 16 16");
    svg.setAttribute("fill", "none");
    svg.setAttribute("stroke", "currentColor");
    svg.setAttribute("stroke-width", "1");
    svg.setAttribute("stroke-linecap", "round");
    svg.setAttribute("stroke-linejoin", "round");
    const polyline1 = document.createElementNS(svgNS, "polyline");
    polyline1.setAttribute("points", "1,10 1,15 6,15");
    svg.appendChild(polyline1);
    const polyline2 = document.createElementNS(svgNS, "polyline");
    polyline2.setAttribute("points", "15,10 15,15 10,15");
    svg.appendChild(polyline2);
    const polyline3 = document.createElementNS(svgNS, "polyline");
    polyline3.setAttribute("points", "1,6 1,1 6,1");
    svg.appendChild(polyline3);
    const polyline4 = document.createElementNS(svgNS, "polyline");
    polyline4.setAttribute("points", "15,6 15,1 10,1");
    svg.appendChild(polyline4);
    fullscreenBtn.appendChild(svg);
    this.styleButton(fullscreenBtn);
    fullscreenBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.openFullscreenModal(state);
    });
    return this.addResizeHandles(container, contentWrapper, state);
  }
  styleButton(btn) {
    btn.style.cssText = `
			width: 28px;
			height: 28px;
			border: none;
			background: var(--interactive-normal);
			color: var(--text-normal);
			border-radius: 4px;
			cursor: pointer;
			font-size: 16px;
			display: flex;
			align-items: center;
			justify-content: center;
			transition: background 0.2s;
		`;
  }
  addResizeHandles(container, contentWrapper, state) {
    const cursorClassMap = {
      "nwse-resize": "mermaid-zoom-resizing-nwse",
      "nesw-resize": "mermaid-zoom-resizing-nesw",
      "ns-resize": "mermaid-zoom-resizing-ns",
      "ew-resize": "mermaid-zoom-resizing-ew"
    };
    const handles = [
      { position: "top-left", cursor: "nwse-resize", style: "top: 0; left: 0; width: 12px; height: 12px;" },
      { position: "top-right", cursor: "nesw-resize", style: "top: 0; right: 0; width: 12px; height: 12px;" },
      { position: "bottom-left", cursor: "nesw-resize", style: "bottom: 0; left: 0; width: 12px; height: 12px;" },
      { position: "bottom-right", cursor: "nwse-resize", style: "bottom: 0; right: 0; width: 12px; height: 12px;" },
      { position: "top", cursor: "ns-resize", style: "top: 0; left: 12px; right: 12px; height: 6px;" },
      { position: "bottom", cursor: "ns-resize", style: "bottom: 0; left: 12px; right: 12px; height: 6px;" },
      { position: "left", cursor: "ew-resize", style: "top: 12px; bottom: 12px; left: 0; width: 6px;" },
      { position: "right", cursor: "ew-resize", style: "top: 12px; bottom: 12px; right: 0; width: 6px;" }
    ];
    const documentListeners = [];
    let currentMarginLeft = 0;
    let currentMarginTop = 0;
    handles.forEach(({ position, cursor, style }) => {
      const handle = container.createDiv(`mermaid-resize-${position}`);
      handle.style.cssText = `
				position: absolute;
				${style}
				cursor: ${cursor};
				z-index: 50;
			`;
      const resizeClass = cursorClassMap[cursor];
      let isResizing = false;
      let startX = 0;
      let startY = 0;
      let startWidth = 0;
      let startHeight = 0;
      let startMarginLeft = 0;
      let startMarginTop = 0;
      const onMouseDown = (e) => {
        e.preventDefault();
        e.stopPropagation();
        isResizing = true;
        startX = e.clientX;
        startY = e.clientY;
        startWidth = container.offsetWidth;
        startHeight = container.offsetHeight;
        startMarginLeft = currentMarginLeft;
        startMarginTop = currentMarginTop;
        document.body.addClass(resizeClass);
      };
      const onMouseMove = (e) => {
        if (!isResizing)
          return;
        e.preventDefault();
        const deltaX = e.clientX - startX;
        const deltaY = e.clientY - startY;
        let newWidth = startWidth;
        let newHeight = startHeight;
        let newMarginLeft = startMarginLeft;
        let newMarginTop = startMarginTop;
        if (position.includes("right")) {
          newWidth = Math.max(150, startWidth + deltaX);
        } else if (position.includes("left")) {
          const widthDelta = -deltaX;
          newWidth = Math.max(150, startWidth + widthDelta);
          if (newWidth > 150) {
            newMarginLeft = startMarginLeft + deltaX;
          }
        }
        if (position.includes("bottom")) {
          newHeight = Math.max(100, startHeight + deltaY);
        } else if (position.includes("top")) {
          const heightDelta = -deltaY;
          newHeight = Math.max(100, startHeight + heightDelta);
          if (newHeight > 100) {
            newMarginTop = startMarginTop + deltaY;
          }
        }
        container.style.width = `${newWidth}px`;
        container.style.height = `${newHeight}px`;
        container.style.marginLeft = `${newMarginLeft}px`;
        container.style.marginTop = `${newMarginTop}px`;
        currentMarginLeft = newMarginLeft;
        currentMarginTop = newMarginTop;
      };
      const onMouseUp = () => {
        if (!isResizing)
          return;
        isResizing = false;
        document.body.removeClass(resizeClass);
        this.resetZoom(contentWrapper, state);
      };
      handle.addEventListener("mousedown", onMouseDown);
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
      documentListeners.push(
        { type: "mousemove", fn: onMouseMove },
        { type: "mouseup", fn: onMouseUp }
      );
    });
    return () => {
      for (const { type, fn } of documentListeners) {
        document.removeEventListener(type, fn);
      }
    };
  }
  addWheelZoom(container, contentWrapper, state) {
    const wheelHandler = (e) => {
      e.preventDefault();
      const rect = container.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;
      const delta = e.deltaY > 0 ? 0.9 : 1.1;
      const oldScale = state.scale;
      let newScale = oldScale * delta;
      newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
      if (newScale !== oldScale) {
        const scaleRatio = newScale / oldScale;
        state.translateX = mouseX - (mouseX - state.translateX) * scaleRatio;
        state.translateY = mouseY - (mouseY - state.translateY) * scaleRatio;
        state.scale = newScale;
        this.updateTransform(contentWrapper, state);
      }
    };
    container.addEventListener("wheel", wheelHandler, { passive: false });
    return () => container.removeEventListener("wheel", wheelHandler);
  }
  addDragPan(container, contentWrapper, state) {
    contentWrapper.classList.add("mermaid-zoom-content");
    container.addEventListener("mousedown", (e) => {
      if (e.button === 0) {
        state.isDragging = true;
        state.startX = e.clientX - state.translateX;
        state.startY = e.clientY - state.translateY;
        contentWrapper.addClass("dragging");
      }
    });
    const onMouseMove = (e) => {
      if (state.isDragging) {
        e.preventDefault();
        state.translateX = e.clientX - state.startX;
        state.translateY = e.clientY - state.startY;
        this.updateTransform(contentWrapper, state);
      }
    };
    const onMouseUp = () => {
      if (state.isDragging) {
        state.isDragging = false;
        contentWrapper.removeClass("dragging");
      }
    };
    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
    return () => {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
    };
  }
  addTouchGestures(container, contentWrapper, state) {
    let initialDistance = 0;
    let initialScale = 1;
    const onTouchStart = (e) => {
      if (e.touches.length === 2) {
        const touch1 = e.touches[0];
        const touch2 = e.touches[1];
        initialDistance = Math.hypot(
          touch2.clientX - touch1.clientX,
          touch2.clientY - touch1.clientY
        );
        initialScale = state.scale;
      } else if (e.touches.length === 1) {
        state.isDragging = true;
        state.startX = e.touches[0].clientX - state.translateX;
        state.startY = e.touches[0].clientY - state.translateY;
      }
    };
    const onTouchMove = (e) => {
      e.preventDefault();
      if (e.touches.length === 2) {
        const touch1 = e.touches[0];
        const touch2 = e.touches[1];
        const currentDistance = Math.hypot(
          touch2.clientX - touch1.clientX,
          touch2.clientY - touch1.clientY
        );
        const scaleRatio = currentDistance / initialDistance;
        let newScale = initialScale * scaleRatio;
        newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
        state.scale = newScale;
        this.updateTransform(contentWrapper, state);
      } else if (e.touches.length === 1 && state.isDragging) {
        state.translateX = e.touches[0].clientX - state.startX;
        state.translateY = e.touches[0].clientY - state.startY;
        this.updateTransform(contentWrapper, state);
      }
    };
    const onTouchEnd = () => {
      state.isDragging = false;
    };
    container.addEventListener("touchstart", onTouchStart);
    container.addEventListener("touchmove", onTouchMove, { passive: false });
    container.addEventListener("touchend", onTouchEnd);
    return () => {
      container.removeEventListener("touchstart", onTouchStart);
      container.removeEventListener("touchmove", onTouchMove);
      container.removeEventListener("touchend", onTouchEnd);
    };
  }
  zoom(contentWrapper, state, factor) {
    let newScale = state.scale * factor;
    newScale = Math.max(state.minScale, Math.min(state.maxScale, newScale));
    const container = contentWrapper.parentElement;
    if (container) {
      const rect = container.getBoundingClientRect();
      const centerX = rect.width / 2;
      const centerY = rect.height / 2;
      const scaleRatio = newScale / state.scale;
      state.translateX = centerX - (centerX - state.translateX) * scaleRatio;
      state.translateY = centerY - (centerY - state.translateY) * scaleRatio;
    }
    state.scale = newScale;
    this.updateTransform(contentWrapper, state);
  }
  resetZoom(contentWrapper, state) {
    this.fitToContainer(state.container, contentWrapper, state.svg, state);
  }
  updateTransform(contentWrapper, state) {
    contentWrapper.style.transform = `translate(${state.translateX}px, ${state.translateY}px) scale(${state.scale})`;
    if (state.scaleIndicator) {
      state.scaleIndicator.textContent = `${Math.round(state.scale * 100)}%`;
    }
  }
  onunload() {
    console.debug("Unloading Mermaid Zoom plugin");
    if (this.mutationObserver) {
      this.mutationObserver.disconnect();
    }
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
    }
    this.zoomStates.clear();
    this.processedElements = /* @__PURE__ */ new WeakSet();
  }
};

/* nosourcemap */